include: package:lint/strict.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_use_package_imports: false

analyzer:
  errors:
    parameter_assignments: error
